Some improvements
gregorio-project/gregorio-project.github.io pull request #56
Opened 2017-03-17 14:42 UTC by martindonat

I was able to finish what I promised in issue #44 

Have a look there for the description.

2017-03-17 15:19 UTC, rpspringuel requested changes

2017-03-17 15:19 UTC, rpspringuel commented on gregoriotex/details.html
> +<li><code>\gresetgregoriofont[op]{parmesan}</code> uses the Dominican variant of the Parmesan font for the neumes.</li>
`parmesan` was renammed to `granapadano`

2017-03-17 15:19 UTC, rpspringuel commented on gregoriotex/index.html
> +<p>This page describes quickly the origin and the construction of Gregorio<span class="tex">T<span class="epsilon">e</span>X</span>. You can also take a look at the <a href="./details.html">Gregorio<
You're linking to `details.html` twice.

2017-03-17 15:19 UTC, rpspringuel commented on gregoriotex/details.html
> +	    <td><i>footnote-size italics</i></td>
I haven't checked, but I'm pretty sure that there's a difference in the formatting for PlainTeX here as changing font size is very difficult in PlainTeX and so we don't generally do it.

2017-03-17 15:21 UTC, martindonat commented on gregoriotex/details.html
> +	    <td><i>footnote-size italics</i></td>
I copied it just from the Reference. See p.30 of the 4.2 Ref

2017-03-17 15:21 UTC, martindonat commented on gregoriotex/details.html
> +<li><code>\gresetgregoriofont[op]{parmesan}</code> uses the Dominican variant of the Parmesan font for the neumes.</li>
Ok, I just corrected the command. Will add that

2017-03-17 15:25 UTC, martindonat commented on gregoriotex/index.html
> +<p>This page describes quickly the origin and the construction of Gregorio<span class="tex">T<span class="epsilon">e</span>X</span>. You can also take a look at the <a href="./details.html">Gregorio<
Right, but there is no GTeX introduction page. So I will just delete the first half of the sentence?

2017-03-17 15:32 UTC, martindonat commented
I updated my repository. Do I have to open a new pull request?

2017-03-17 16:41 UTC, henryso commented
As long as you make them in the same branch and push that (which you apparently did), that will update the associated (in this case, this) pull request.

2017-03-17 17:27 UTC, rpspringuel commented on gregoriotex/details.html
> +	    <td><i>footnote-size italics</i></td>
That may just mean that the reference manual needs to be corrected too.

2017-03-17 17:31 UTC, rpspringuel requested changes

2017-03-17 17:31 UTC, rpspringuel commented on gregoriotex/details.html
> +<li><code>\gresetgregoriofont[op]{granapadano}</code> uses the Dominican variant of the Granapadano font for the neumes.</li>
I should have been more clear.  The font name is Grana Padano, this becomes `granapadano` for the filename and as the argument of the function.

2017-03-17 17:34 UTC, rpspringuel commented on gregoriotex/details.html
> +	    <td><i>footnote-size italics</i></td>
I just checked `gregoriotex.tex` (where this style is defined for PlainTeX) and it is as I thought.  I'll see about correcting reference manual.

2017-03-20 12:31 UTC, martindonat commented
Now it should ready.

2017-03-20 14:03 UTC, rpspringuel approved these changes

2017-03-20 14:04 UTC, rpspringuel requested changes

2017-03-20 14:04 UTC, rpspringuel commented on gregoriotex/details.html
> +	    <td><i>footnote-size italics</i></td>
I've fixed the reference manual.  If you could please fix this too.

2017-03-20 14:23 UTC, martindonat commented
Ok?

2017-03-20 14:25 UTC, rpspringuel approved these changes
Looks good.

2017-03-20 17:37 UTC, merged

2017-03-20 18:07 UTC, martindonat commented
Sorry, I found another mistake, due to my incompetence regarding Git...

I corrected it in my repo.

2017-03-20 18:13 UTC, rpspringuel commented
Since I've merged this PR, you'll need to create another one at this point.